version: "3"
services:
  
  ecommerce-app:
  
    build: ${ECOMMERCE_SERVICE_PATH}/Docker/app/.
    container_name: ${ECOMMERCE_SERVICE_NAME}
    command: ["npm", "run", "dev"]
    env_file:
      - ${ECOMMERCE_SERVICE_PATH}/Docker/app/.env
      - .env
    environment:
      - SEQUELIZE_HOST=${ECOMMERCE_MYSQL_NAME}
      - SEQUELIZE_DATABASE=${ECOMMERCE_MYSQL_DATABASE}
    volumes:
      - ${ECOMMERCE_SERVICE_PATH}/seeders:/app/seeders
      - ${ECOMMERCE_SERVICE_PATH}/config:/app/config
      - ${ECOMMERCE_SERVICE_PATH}/src:/app/src
      - ${ECOMMERCE_SERVICE_PATH}/tests:/app/tests
    ports:
      - ${ECOMMERCE_APP_PORT}:8080
    depends_on:
      - ecommerce-mysql
  ecommerce-mysql:
    
    platform: linux/x86_64
    build: ${ECOMMERCE_SERVICE_PATH}/Docker/database/.
    restart: always
    container_name: ${ECOMMERCE_MYSQL_NAME}
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${ECOMMERCE_MYSQL_DATABASE}
    ports:
      - ${ECOMMERCE_MYSQL_PORT}:3306
    command: ["--default-authentication-plugin=mysql_native_password", "--init-file", "/docker-entrypoint-initdb.d/init.sql"]
    volumes:
      - db_data:/var/lib/mysql
      - .docker/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
    db_data: